apiVersion: v1
kind: Service
metadata:
  name: senatus-config-server-nodeport
  labels:
    app: senatus
spec:
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30008
  selector:
    app: senatus
    tier: config-server
