apiVersion: apps/v1
kind: Deployment
metadata:
  name: senatus-config-server
  labels:
    app: senatus
spec:
  selector:
    matchLabels:
      app: senatus
      tier: config-server
  strategy:
    type: Recreate
  template:
    metadata:
      name: config-server-pod
      labels:
        app: senatus
        tier: config-server
    spec:
      containers:
      - name: config-server
        image: config-server:1.0.0
