server:
  port: 8182
spring:
  profiles: development
  data:
## MongoDb
    mongodb:
      host: senatus-mongo-server
      port: 27017
      database: mydatabase
## RabbitMQ
  rabbitmq:
    host: senatus-rabbit-server
    username: country-document
    password: country-document