spring:
  profiles: development
  application:
    name: location-cache
  datasource:
    hikari:
      connectionTimeout: 20000
    maximumPoolSize: 5
    url: jdbc:postgresql://192.168.1.249:5432/senatus_web
    username: postgres
    password: postgresqlpwd
  rabbitmq:
    host: 192.168.1.249
    listener:
      simple:
        default-requeue-rejected: false
    username: country-app
    password: country-app
  cloud:
    function:
      definition: consumer
    stream:
      bindings:
        consumeCountryCacheEvent-in-0:
          destination: new-location-country.v1
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: env, health, info, loggers, metrics